language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*

before_install:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install: composer install --prefer-dist --no-interaction

script: bin/phpunit -c . --coverage-text
